version: 2
jobs:
  build:
    working_directory: ~/web-workbook
    docker:
    - image: circleci/node:8.9.4
    steps:
    - checkout
    - restore_cache:
        keys:
        - v2-dep-{{ .Branch }}-
        - v2-dep-gh-pages-
        - v2-dep-
    - run: npm install
    - save_cache:
        key: v2-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ./node_modules
    - run: npm run lint
